### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by stresslimit** [Automattic/custom-metadata#126]
If so, what is the Automattic-preferred way to sanely manage custom fields?

@mjangda @jkudish hello

**Comment by mjangda** [comment]
We've mostly held back from any major updates because of the ongoing Meta project in core (also, lack of time :)). However, the plugin should still work so nothing's stopping folks from using it. <a href="http://fieldmanager.org/">Fieldmanager</a> is also a pretty good alternative.

**Comment by stresslimit** [comment]
Cool I was wondering if there was a core effort going on, I'm pretty far away from core at the moment. Is that [this one](https://github.com/sc0ttkclark/wordpress-fields-api)?

**Comment by mjangda** [comment]
That's the one!

**Comment by stresslimit** [comment]
Awesome. Gonna keep using our old faithful here til the new paradigm hits core. Thanks!
